### ISSUE TITLE
fix boosting formula page

### ISSUE THREAD

**Issue by MarcoWorms** [CurveDocs/curve-resources#10]
https://resources.curve.fi/reward-gauges/boosting-your-crv-rewards/#Formula

the section on "Formula" looks unfinished, it doesn't explain how you go from the newly named "earning weight" to the boost, nor how that will be used to compute the yield, it's also problematic (but one from the old page) in that none of these terms like "DollarProvided", "TotalLiquidity" are explained, and that is not a weight exactly it’s a balance, maybe the coefficient of it could be considered a weight

**Comment by mo-anon** [comment]
fixed in: https://github.com/CurveDocs/curve-resources/pull/75
